### PR TITLE
update the eaglerxbungee files

### PR DESCRIPTION
**Pull request by grandpa1946**

### CODE REVIEW

**Comment by OtterCodes102** [comment]
isn't it 1.0.7?

**Comment by grandpa1946** [comment]
> isn't it 1.0.7?

they skipped 1.0.7: https://github.com/lax1dude/eagl3rxbungee-memory-leak-patch/commit/aaab693dcea509c005e9cabf12c75d1d086ed9ee

**Comment by OtterCodes102** [comment]
huh.

**Comment by grandpa1946** [comment]
> huh.

wdym?

**Comment by OtterCodes102** [comment]
nothing, i didn't know it came out ¯\_(ツ)_/¯

**Pull request merged**
